### ISSUE TITLE
Add the ability to pass a delimited list of .env files

### ISSUE THREAD

**Issue by jclausen** [elpete/commandbox-dotenv#14]
Blocked by issue #13, when a custom `.env` file is provided, allow a delimited list of multiple files which may be sourced in.  

A use case might be:

1.  file with globals ( e.g. database credentials )
2. file with app-specific settings ( e.g. database name )
3. file with modular environmental variables

**Comment by elpete** [comment]
Can you give an example of how the lookup would occur, in your opinion?

**Comment by jclausen** [comment]
Probably a nested key like other CommandBox modules do:

```
{
   "dotenv" : {
       "filename" : "W:\\Apps\\.machine.env,.my.domain.com.env
   }
}
```

Then explode the list to an array and source each one in.  It should be able to support relative or absolute paths.

**Comment by bdw429s** [comment]
This should be closed by https://github.com/commandbox-modules/commandbox-dotenv/pull/21
