### ISSUE TITLE
Check for a new `.env` file after certain CommandBox commands

### ISSUE THREAD

**Issue by elpete** [elpete/commandbox-dotenv#3]
Here's how I envision this one going:

Using both a `preCommand` and `postCommand` interceptor, check if the command executed changed the current directory.  If it did, check for an `.env` file.  If one is found, load it and inform the user in the console.

**Comment by bdw429s** [comment]
This should be fixed by https://github.com/elpete/commandbox-dotenv/pull/9 which more generically just loads env vars before any command, but only into the environment context of that command, so they automatically clean up after.

**Comment by elpete** [comment]
Resolved in v1.6.0 / #9
